version: "3.9"
services:
  hetzner-load-balancer-prometheus-exporter:
    image: test
    container_name: hetzner-lb
    ports:
      - 8000
    environment:
      LOAD_BALANCER_IDS: 'all'
      ACCESS_TOKEN: ''
      SCRAPE_INTERVAL: '30'
